url: "https://mrspidercat.github.io"
baseurl: "/Loyal-MC-Site"
siteIcon: /media/android-chrome-192x192.png
siteYear: 2021
siteFooterlink: /about
showinSearchEngines: true


# Set basic server info
serverName: Loyal MC
serverDescription: Loyal MC is a Bedrock Edition and Java Edition Crossplay survival server that allows for both Minecraft editions to play together!  
serverIP: hypixel.net
useBedrockForOnlineStatus: false


# Discord information
discordInvite: https://discord.gg/DpcBUveEta
discordServerID: 776591490872639519
discordChannelID: 817925193330458624


# # Navbar Links at the top of the page (uncomment "siteNav" to use)
# #   name - The title on the navbar
# #   url - The link it should go to (for example, if you have "maps.md" file, put "maps")
# #   newtab - Whether link should open in new tab
# 
siteNav:
   - name: Rank Shop
     url: shop
   - name: Modpack
     url: modpack
   - name: About
     url: about
#   - name: Server Map
#     url: map
#     newtab: true

# Don't change anything below here, these are defaults set by GitHub Pages:
# ======
theme: minima
# plugins:
#   - jekyll-feed
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
